import { StyleSheet } from 'react-native';
import { COLORS, FONTS } from '../colors';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: COLORS.background },
  container: { flex: 1, backgroundColor: COLORS.background },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 24 },
  loadingWordmark: { fontSize: 22, fontWeight: '800', letterSpacing: 4, color: COLORS.accent, marginBottom: 24 },
  loadingSpinner: { marginBottom: 16 },
  loadingText: { color: COLORS.textSecondary, fontSize: 14 },
  errorCard: { width: '100%', backgroundColor: COLORS.surface, borderWidth: 1, borderColor: COLORS.surfaceBorder, borderRadius: 16, padding: 24, alignItems: 'center' },
  errorGlyph: { fontSize: 28, marginBottom: 12 },
  errorText: { fontSize: 16, fontWeight: '700', color: COLORS.textPrimary, marginBottom: 6, textAlign: 'center' },
  errorSub: { fontSize: 14, color: COLORS.textSecondary, textAlign: 'center', marginBottom: 20, lineHeight: 20 },
  primaryButton: { backgroundColor: COLORS.accent, paddingVertical: 12, paddingHorizontal: 28, borderRadius: 10 },
  primaryButtonText: { color: COLORS.background, fontWeight: '700', fontSize: 15 },
  masthead: { paddingHorizontal: 20, paddingTop: 64, paddingBottom: 20 },
  eyebrowRow: { flexDirection: 'row', alignItems: 'baseline', marginBottom: 18 },
  wordmark: { fontSize: 15, fontWeight: '800', letterSpacing: 3, color: COLORS.accent },
  eyebrow: { fontSize: 11, fontWeight: '600', letterSpacing: 2, color: COLORS.textTertiary, marginLeft: 8, fontFamily: FONTS.mono },
  greeting: { fontSize: 30, fontWeight: '800', color: COLORS.textPrimary, letterSpacing: -0.5 },
  date: { fontSize: 15, color: COLORS.textSecondary, marginTop: 4 },
  hairline: { height: 1, backgroundColor: COLORS.surfaceBorder, marginTop: 18, marginBottom: 14 },
  statsRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  statBadge: { backgroundColor: COLORS.accentMuted, paddingVertical: 6, paddingHorizontal: 12, borderRadius: 999 },
  statBadgeText: { color: COLORS.accent, fontSize: 12, fontWeight: '700' },
  syncLabel: { color: COLORS.textTertiary, fontSize: 12, fontFamily: FONTS.mono },
  emptyState: { alignItems: 'center', paddingHorizontal: 32, paddingTop: 60 },
  emptyGlyph: { fontSize: 40, marginBottom: 16 },
  emptyTitle: { fontSize: 18, fontWeight: '700', color: COLORS.textPrimary, marginBottom: 8 },
  emptySubtitle: { fontSize: 14, color: COLORS.textSecondary, textAlign: 'center', lineHeight: 20, marginBottom: 20 },
  secondaryButton: { borderWidth: 1, borderColor: COLORS.surfaceBorder, paddingVertical: 10, paddingHorizontal: 20, borderRadius: 10 },
  secondaryButtonText: { color: COLORS.textPrimary, fontWeight: '600', fontSize: 14 },
  listPadding: { paddingHorizontal: 16, paddingBottom: 32 },
  listPaddingEmpty: { flexGrow: 1, paddingHorizontal: 16, paddingBottom: 32 },
});
